variable "tag_name_prefix" {}
variable "iam_instance_profile" {}
variable "vpc_id" {}
variable "private_subnet1_id" {}
variable "private_subnet2_id" {}
variable "instance_type" {}
#variable "key_name" {}
variable "security_group_alb_id" {}
variable "alb" {}
variable "alb_target_group" {}